@startuml calluml

skinparam DefaultFontName "思源黑体"
skinparam DefaultFontSize 18

App -> Window : 触发事件
Window -> Button1 : 传递事件
Button1 -> Label1 : 传递事件
note right
    对象如果具有父子关系，
    则事件触发顺序一定是
    从父对象到子对象
end note
Label1 -> Button1 : 事件响应
note left
    具有同一父对象的Block
    事件触发顺序是由其的
    zindex决定
end note
Button1 -> Group1 : 传递事件
Group1 -> Button2 : 传递事件
Button2 -> Label2 : 传递事件
Label2 -> Button2 : 事件响应
note left
    如果zindex相同，事件触发顺序是不
    确定的，它有可能是对象的添加顺序
end note
Button2 -> Button3 : 传递事件
Button3 -> Label3 : 传递事件
Label3 -> Button3 : 事件响应
Button3 -> Group1 : 事件响应
Group1 -> Window : 事件响应
Window -> App : 事件响应


@enduml