@startuml 事件循环在一帧内的处理流程

skinparam defaultFontName "思源黑体"
skinparam DefaultFontSize 16

start
:启动程序;
while (事件循环)
    #LightSteelBlue:触发 Block::paintEvent(PaintEvent);
    -[#Blue]->
    while (是否即将需要渲染下一帧?) is (否)
        if(是否存在键盘消息)then(是)
            #LightYellow:捕获键盘消息;
            if(是否为按键消息)then(是)
                if(是否为按键按下消息)then(是)
                    #LightSteelBlue:触发 Block::keyPressEvent(Key,KeyFlag);
                else if(是否为按键释放消息)then(是)
                    #LightSteelBlue:触发 Block::keyReleaseEvent(Key,KeyFlag);
                else if(是否为Unicode字符输入消息)then(是)
                    #LightSteelBlue:触发 Block::InputTextEvent(wchar_t);
                endif
            else (否)
            endif
            if(是否为字符(ASCII)消息)then(是)
                #LightSteelBlue:触发 Block::InputCharEvent(wchar_t);
            else (否)
            endif
        endif
        if(是否存在鼠标消息)then(是)
            #LightYellow:捕获鼠标消息;
            if(是否为鼠标按键按下消息)then(是)
                #LightSteelBlue:触发 Block::mousePressEvent(Point,MouseButton);
            else (否)
            endif
            if(是否为鼠标按键释放消息)then(是)
                #LightSteelBlue:触发 Block::mouseReleaseEvent(Point,MouseButton);
            else (否)
            endif
            if(是否为鼠标滚轮消息)then(是)
                #LightSteelBlue:触发 Block::wheelEvent(Point,MouseWheel);
            else (否)
            endif
            if(是否为鼠标移动消息)then(是)
                #LightSteelBlue:触发 Block::mouseMoveEvent(Point);
            else (否)
            endif
        else (否)
        endif
    endwhile (是)
endwhile
:退出程序;
stop

@enduml